export const TextoComentarios = [
  'Eu comprei o %produto% e absolutamente adorei. Foi uma compra que valeu a pena!',
  'Eu realmente gostei deste %produto% e definitivamente compraria novamente.',
  'O %produto% superou minhas expectativas - estou muito satisfeito com a minha compra.',
  'Este %produto% foi exatamente o que eu estava procurando. Não poderia estar mais feliz.',
  'A qualidade deste %produto% é incrível. Recomendo.',
  'Eu comprei este %produto% como um presente e meu amigo amou - foi uma escolha perfeita.',
  'Comprei e valeu a pena o dinheiro investido.',
  'Este %produto% é incrível - mal posso esperar para comprar mais coisas dessa empresa.',
  'Fiquei muito impressionado com a rapidez e qualidade no atendimento!',
  'Eu amei tudo sobre o %produto%. Valeu cada centavo.',
  'O %produto% realmente tornou minha vida mais fácil! Estou muito feliz por tê-lo comprado.',
  'Este %produto% é de alta qualidade - não posso esperar para começar a usar.',
  'Este %produto% superou minhas expectativas e realmente melhorou minha rotina diária.',
  'Foi tão fácil comprar o %produto% - estou muito satisfeito com a minha experiência de compra.',
  'Eu comprei este %produto% para experimentar algo novo e fiquei agradavelmente surpreso com o resultado.',
  'O %produto% não só é funcional, mas também é incrivel . Estou muito feliz por tê-lo comprado.',
  'Comprei este %produto% para dar de presente e a pessoa que recebeu adorou - definitivamente uma escolha acertada.',
  'O %produto% é tão versátil e útil - não sei como vivi sem ele antes!',
  'Fiquei muito impressionado com o atendimento ao cliente ao comprar este %produto% - a equipe foi muito prestativa e atenciosa.',
  'Comprei o %produto% e imediatamente percebi a diferença - é incrível como pequenas coisas podem fazer uma grande diferença!',
  'Este %produto% não só é de alta qualidade, mas também é muito acessível. Eu não poderia estar mais feliz com minha compra.',
  'Comprar este %produto% foi uma decisão de última hora, mas estou tão feliz por ter feito.',
  'Foi um ótimo investimento. Ótimo custo x benefício. ',
  'Só tenho elogios, pois realmente cumpri o prometido!',
  'O %produto% é perfeito para mim - fiquei tão feliz por ter encontrado algo que se encaixasse tão bem no meu estilo de vida.',
  'Este %produto% foi uma ótima escolha. Fiquei tão feliz com os resultados e com a experiência de compra como um todo.',
  'Estou tão satisfeito com este %produto% que recomendei a amigos e familiares - definitivamente vale a pena o investimento.',
  'Wow! Gostei da ideia, acho que vou comprar!',
  'Estava na dúvida, mas com esse preço... Mais barato do que eu imaginava. Vou aproveitar hehehehe',
  'Mal posso esperar para ver todas as maneiras que posso usar',
  'Este %produto% é a solução perfeita para meu problema de longa data - estou muito satisfeito com minha compra.',
  'Comprei este %produto% em um impulso e não poderia estar mais feliz - acabou sendo exatamente o que eu precisava.',
  'O %produto% é tão inovador e útil. Super recomendo :)',
  'Comprei este %produto% e imediatamente o integrei à minha rotina - agora não consigo mais viver sem ele!',
  'Este %produto% é tão simples, mas tão eficaz que fiquei impressionado com o quão bem ele funciona.',
  'Comprar o %produto% foi uma ótima decisão - estou muito feliz por ter tomado a iniciativa.',
  'Este %produto% superou minhas expectativas. a qualidade é incrível.',
  'Comprei este %produto% para um projeto específico e fiquei tão feliz com o resultado final.',
  'O %produto% me ajudou a economizar tempo e energia - estou muito grato por tê-lo comprado.',
  'Produto d+! Ammoooo!',
  'Eu estava um pouco preocupado com a qualidade do %produto%, mas depois de experimentá-lo, fiquei muito satisfeito!',
  'Comprei este produto como uma opção mais barata, mas fiquei surpreso com a qualidade - realmente valeu a pena!',
  'O processo de compra foi fácil e sem complicações - definitivamente comprarei novamente no futuro!',
  'Eu recomendo o %produto% a todos que conheço é simplesmente incrível',
  'Já tive algumas experiências ruins comprando online, mas dessa vez foi tudo certinho.',
  'Comprar online é muito conveniente e economiza tempo. O site apresenta todas as informações necessárias para me dar segurança.',
  'Processo de compra simple e rápido! Recomendo sem medo.',
  'Acabei de receber meu pedido e estou muito feliz com a qualidade.',
  'Comprei o %produto% porque estava em promoção e achei o preço muito bom. Agradeço pelo bom atendimento.',
  'Foi a primeira vez que comprei dessa loja e fiquei impressionado com o atendimento.',
  'Achei o material muito interessante e bem estruturado. Estou gostando.',
  'Até agora não tive problemas. Pretendo testar e avaliar bem o investimento.',
  'Material de primeira qualidade! Top!',
  'Antes de comprar pesquisei muito e não me arrependo da compra.',
  'Pelo preço achei que iria me decepcionar e me arrepender da compra, mas para minha surpresa, foi o melhor negócio que fiz.'
];

export const TextoRespostas = [
  'Fiquei felize em ouvir que a sua experiência de compra foi boa. ',
  'Acho que o %produto% irá atender às minhas expectativas também.',
  'Quero facilidade! Vou esperimentar e ver se realmente é bom.',
  'Obrigado pelo seu comentário! Espero gostar dele tanto quanto vc.',
  'Concordo totalmente! É ótimo quando você pode fazer uma escolha de qualidade sem sacrificar a eficácia.',
  'O preço realmente está bom!',
  'Parece até bom de mais pra ser verdade hehehe',
  'Nada me deixaria mais feliz do que saber que foi um bom investimento.',
  'Ótimo feedback! Agora tenho mais segurança com a compra.',
  'E o atendimento deles??? Véio, show de bola!',
  'Gostei. Ansioso para começar a usar.',
  'Que legal! Estou animado ;)',
  'Obrigado por me recomendar a compra! ',
  'Será que ficarei tão feliz com o %produto%? Espero que sim.',
  'Esse %produto% está fazendo a diferença na minha vida.',
  'Também acho... ',
  'Concordo sim! Eu comprei o mesmo %produto% e também fiquei muito satisfeito com ele.',
  'Ótimo custo/benefício.',
  'Realmente parece ser uma ótima escolha para quem busca qualidade e praticidade.',
  'Eu estava procurando um produto semelhante há muito tempo e este acabou sendo perfeito',
  'É sempre gratificante quando um produto atende às nossas expectativas e resolve nossos problemas.',
  'Eu estava um pouco cético em relação ao %produto%, mas depois que o comprei, percebi que ele realmente funciona!',
  'Entendo como é difícil confiar em um produto novo, mas depois que dei uma chance, acabou valendo a pena.',
  'Eu comprei este %produto% como presente para um amigo e ele adorou!',
  'Quero ser feliz também kkkkkkkkkk',
  'Não posso acreditar no quão barato está o %produto%!',
  'Barato e ainda assim, tem uma qualidade excelente',
  'Sim, às vezes podemos encontrar ótimas ofertas sem comprometer a qualidade. ',
  'Que sorte a minha de ter achado esse link.',
  'Comprei este %produto% há alguns meses e estou satisfeito.',
  'Obrigado por compartilhar sua experiência!',
  'Estou muito feliz por tê-lo comprado!',
  'Espero continuar a desfrutar dele por um bom tempo',
  'Recebi o %produto% rapidamente. A Compra foi muito fácil.',
  'Fiquei impressionado com a eficiência do processo!',
  'Espero ter uma ótima experiência com o %produto% também!',
  'Gostei muito do resultado.',
  'Atendeu todas as expectativas :) \o/',
  'Esse %produto% me ajudou a resolver um problema específico. Gostei.',
  'Eu estava um pouco cético em relação a comprar online, mas depois que recebi o %produto%, mudei de ideia foi uma ótima experiência!',
  'Acho que valeu a pena.',
  'Foi minha primeira compra pela internet. Estava com medo, mas correu tudo bem.',
  'Este %produto% superou todas as minhas expectativas - é realmente incrível!',
  'Comprei o %produto% como uma solução temporária, mas acabei gostando tanto que agora é um item essencial para mim!',
  'Obrigado por compartilhar sua experiência e espero que continue a desfrutar dele',
  'Este %produto% tem sido um salva-vidas para mim - definitivamente valeu a pena o investimento!',
  'Tormou a minha vida melhor rsrsrsrssrrr',
  'Às vezes, produtos mais baratos podem ser tão bons quanto ou até melhores que os mais caros.',
  'Este se encaixou perfeitamente no que eu buscava, estou muito satisfeito!',
  'Este %produto% me ajudou a economizar muito tempo e dinheiro - estou muito grato!',
  'O %produto% é perfeito para minhas necessidades específicas.',
  'Recomendo fortemente',
  'Cara, que dahora....',
  'É top d+ ;)',
  'Concordo com você. Estou gostando muito.'
];
